### ISSUE TITLE
OrbitingPlanetsDemo.exe

### ISSUE THREAD

**Issue by Divyansh-the-techie** [salutes-space/OrbitingPlanetsDemo#1]
The OrbitingPlanetsDemo file is in the debug folder, and the path given in the readme is wrong. One also needs to find the dll files, which are located in the .\app\_deps\sfml-build\lib\Debug folder, and copy them to the debug folder where OrbitingPlanetsDemo.exe is located to run the program successfully

**Comment by MerlinGiga** [comment]
**Good catch!**

The issue with the incorrect path in the README and the need to manually copy the SFML DLL files to the executable's folder is indeed problematic. This can lead to confusion and platform-specific issues, especially when using CMake, which is designed to ensure cross-platform compatibility.

To address this, here's a CMake-based workaround that automatically copies the required DLLs to the output directory on Windows, avoiding the need for manual intervention. The following code ensures that after the build process, the necessary SFML DLLs are automatically placed in the same folder as `OrbitingPlanetsDemo.exe`:

```cmake
# Automatically copy SFML DLLs to the output directory on Windows
if(WIN32)
    add_custom_command(TARGET OrbitingPlanetsDemo POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${SFML_DIR}/../lib/Debug/sfml-system-d.dll"
        "${SFML_DIR}/../lib/Debug/sfml-window-d.dll"
        "${SFML_DIR}/../lib/Debug/sfml-graphics-d.dll"
        "${SFML_DIR}/../lib/Debug/sfml-network-d.dll"
        "${SFML_DIR}/../lib/Debug/sfml-audio-d.dll"
        $<TARGET_FILE_DIR:OrbitingPlanetsDemo>
    )
endif()
```

This will make sure that when building the project on Windows, the required DLLs are automatically copied to the correct directory, ensuring the program runs smoothly.

**Comment by msfouda** [comment]
Thanks, @Divyansh-the-techie for the nice catch!

@MerlinGiga, Please update the repo accordingly...

**Comment by msfouda** [comment]
I checked out that find_package() and set_target_properties() should solve linking issues on Windows as well.


```
find_package(SFML COMPONENTS system window graphics network audio REQUIRED
                PATHS ${CMAKE_BINARY_DIR}/* 
                NO_DEFAULT_PATH
            )

set_target_properties(OrbitingPlanetsDemo PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
```

Latest version updated on the repo.
